### ISSUE TITLE
Tiny feedback

### ISSUE THREAD

**Issue by luciusmagn** [jKubalec/rust_lesson_2_homework#1]
https://github.com/jKubalec/rust_lesson_2_homework/blob/196815ec8c0aa4148b2d9e8abec3509bf0928602/src/main.rs#L27-L30

You don't need these braces :)

https://github.com/jKubalec/rust_lesson_2_homework/blob/196815ec8c0aa4148b2d9e8abec3509bf0928602/src/main.rs#L31

You are making a useless conversion here, you can just do:

```rust
		_ => {
			"Unknown operation. Original string: ".to_owned() + &raw_string
		}
```

The output of Add<&str> on String produces a new String already, so you are essentially doing `String::from(String)`, which is a no-op

https://github.com/jKubalec/rust_lesson_2_homework/blob/196815ec8c0aa4148b2d9e8abec3509bf0928602/src/main.rs#L29

You can just use a character literal for replacement of a single character, `.replace()` takes both))

**Comment by jKubalec** [comment]
Changes implemented
